version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./realm.json:/tmp/realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/realm.json
    ports:
      - 8080:8080

  frontend:
    build: ./todo-frontend-spa
    image: oidc-pattern-frontend
    container_name: oidc-pattern-frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - keycloak
